import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/src/components'
import { ToastProvider } from '@/src/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="min-h-screen flex flex-col items-center gap-y-5">
          <Header />
          <div className="flex flex-col gap-y-5">
            <ToastProvider>{children}</ToastProvider>
          </div>
        </main>
      </body>
    </html>
  )
}
